### ISSUE TITLE
Webhook: v1beta1 to v1beta2 conversion causes circular errors

### ISSUE THREAD

**Issue by csotiriou** [tmforum-oda/oda-canvas#114]
## Long story short

When we try to upload a component.yaml written in the v1beta1 specification, the conversion succeeds by the webhook in the surface, but under the hood the webhook is creating a **never-ending stream of errors** at an extremely high rate.

## Description

Consider the following component:

```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: oda.tmforum.org/v1beta1
kind: component
metadata:
  labels:
    app.kubernetes.io/instance: samplecomponent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: samplecomponent
    app.kubernetes.io/version: 1.0.1
    argocd.argoproj.io/instance: samplecomponent
    helm.sh/chart: samplecomponent-0.1.40
    oda.tmforum.org/componentName: samplecomponent
  name: samplecomponent-component
spec:
  coreFunction:
    exposedAPIs:
      - apitype: openapi
        implementation: samplecomponent-application
        name: samplecomponent
        path: /geographicAddress
        port: 80
        specification: /swagger-ui/cell-ab
  description: Sample Description
  eventNotification: {}
  maintainers:
    - email: johndoe@ttest.com
      name: Hello World
      url: https://mydomain.com
  management: {}
  owners:
    - email: test@test.test
      name: Hello World
      url: https://mydomain.com
  security:
    dependentAPIs: []
    exposedAPIs: []
    grant_types:
      client_credentials:
        consumerRef: oauth2-samplecomponent-consumer
        credentialRef: samplecomponent-credential
        pluginRefs:
          - oauth2-example
        scopes: []
    type: oauth2
  type: Local
  version: 1.0.0
```

When applied via kubectl apply, we see the conversion of v1beta1 to v1beta2 being successful. However, we notice that kubernetes identifies that something is wrong with this particular resource definition. The below is the image of k9s.

![Screenshot 2023-09-16 at 19 34 28](https://github.com/tmforum-oda/oda-canvas/assets/1228484/579ac966-fce3-4fdd-8607-91bb4bfac263)

Upon further inspection, we retrieve the logs of the `compcrdwebhook` application and put them into a file. 

We notice the following pattern:
```
canvas compcrdwebhook-5b4db8fd76-stsr5 compcrdwebhook Comparing old version oda.tmforum.org/v1beta1 and desired version oda.tmforum.org/v1beta2
canvas compcrdwebhook-5b4db8fd76-stsr5 compcrdwebhook rename security and management segments to securityFunction and managementFunction
canvas compcrdwebhook-5b4db8fd76-stsr5 compcrdwebhook split type into two fields id and name
canvas compcrdwebhook-5b4db8fd76-stsr5 compcrdwebhook add the metadata for functionalBlock
```

This is the normal conversion. Immediately afterwards, we notice, however, strange conversions fo the same component which has already been converted:

```
canvas compcrdwebhook-5b4db8fd76-stsr5 compcrdwebhook --------------------------------------------------------------
canvas compcrdwebhook-5b4db8fd76-stsr5 compcrdwebhook Error converting from  oda.tmforum.org/v1beta2  to  oda.tmforum.org/v1alpha2
canvas compcrdwebhook-5b4db8fd76-stsr5 compcrdwebhook trying to convert object:
Error message:
canvas compcrdwebhook-5b4db8fd76-stsr5 compcrdwebhook Error: The desired API version oda.tmforum.org/v1alpha2 is not supported
canvas compcrdwebhook-5b4db8fd76-stsr5 compcrdwebhook     at /src/app.js:106:15
```

The pattern repeats endlessly with different version combinations of the resource. 

## Additional information
I noticed that the errors are thousands in a few seconds. I decided to put a console.log in line 89 in app.js, use that in kubernetes, and retrieve the logs to see exactly what happens. Please find attached the resulting log.

For debugging, I also changed the code  to the following (lines 101 - 109)

```javascript
 if (!supportedAPIVersions.includes(currentAPIVersion)) {
        console.error("The current API version " + currentAPIVersion + " is not supported")
        continue
      }
      // test if the desiredAPIVersion is in the list of supported versions
      if (!supportedAPIVersions.includes(desiredAPIVersion)) {
        console.error("The desired API version " + desiredAPIVersion + " is not supported")
        continue
      }
```

I did that change so that an error is not thrown when failing due to unsupported versions. Don't know if that was actually correct, but the result was that the calls to the webhook were one in 2 seconds, and not hundreds per second as they were before. However, the errors still remained. Note that the logs attached do NOT have this change - I just did it for debugging.

## System information
* Kubernetes version: 1.27.4

* OS/platform: macOS. Tested with Rancher Desktop, Colima, and orbstack (3 local desktop stacks). 

**Logs from the microservice** [out.log.zip](https://github.com/tmforum-oda/oda-canvas/files/12641156/out.log.zip)

**Comment by LesterThomas** [comment]
It seems that something is requesting a oda.tmforum.org/v1alpha2 version of the components (which is failing). We always support N-2 (current version is v1beta2, so we also support v1beta1, v1alpha4 and so conversion to v1alpha2 is untested/not supported.
The question is what is requesting the v1alpha2 version- this could be one of the operators. Could you check what operators are running and what the image versions of these are?

**Comment by csotiriou** [comment]
@LesterThomas hello, that was my guess, too.

I wish I could find out. This happens in a fresh install of Kubernetes, and no other operator installed
- Installed components: `istiobase`, `istiod`, cert-manager (via the `cert-manager-init` helm chart in this repo), the `webhook` (again, from the helm chart), and the `oda-crds` helm chart also from this repo.

**Comment by csotiriou** [comment]
@LesterThomas I believe I have more information.

Kubernetes will allow you to fetch the resources into all supported versions with the `served` property set to true. For example

```
kubectl get components.v1alpha2.oda.tmforum.org
```

will fetch the component that I have uploaded converted to version v1alpha2. This will trigger a request to the webhook.

Even if the component is updated to v1beta2, the API Server will dynamically convert the resource to the exact version that was requested.  I suppose this is what you meant when asking if there are other operators in the cluster.

Since there is no operator inside the cluster in my case, my non-educated guess is that the API server may want to cache the supported versions since it finds them on the CRD, or something similar. 

Question: Since old versions are not supported and they cannot be converted, maybe they could be removed from the CRD? If this is done, the invalid requests will disappear, and (maybe) that is more correct technically-wise

**Comment by LesterThomas** [comment]
@csotiriou I think you have identified the issue - I just checked the CRD (https://github.com/tmforum-oda/oda-canvas/blob/master/installation/oda-crds/templates/oda-component-crd.yaml) and it is still showing that v1alpha2 is supported:

```
  - name: "v1alpha2"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: false
    deprecated: true
    deprecationWarning: "oda.tmforum.org/v1alpha2 Component is deprecated; Please upgrade to oda.tmforum.org/v1beta1"
    schema:
      openAPIV3Schema:
        type: object
```

Where it should be like the v1alpha1:

```
 - name: "v1alpha1"
    # Each version can be enabled/disabled by Served flag.
    served: false
    # One and only one version must be marked as the storage version.
    storage: false
    deprecated: true
    deprecationWarning: "oda.tmforum.org/v1alpha1 Component is deprecated; Please upgrade to oda.tmforum.org/v1beta1 see https://github.com/tmforum-oda/oda-canvas-charts/issues/19"
    schema:
      openAPIV3Schema:
        type: object
```     

I'll create a fix for this and test it.
