### ISSUE TITLE
crd资源kind大小写的问题 (CRD kind definition should be CamelCase)

### ISSUE THREAD

**Issue by wdt1988520** [tmforum-oda/oda-canvas#164]
Kubernetes 资源kind 通常以大写字母开头的驼峰命名规范，目前oda canvas的api和component 均为小写，这样会导致使用golang语言开发是不能直接使用code-generator和反射，这样的导致开发非常不便。 golang语言的规范大写字母命名开头的对象为外部可访问对象，小写字母开头的为同package可以访问对象。
# kind is normally the CamelCased singular type. Your resource manifests use this.

<img width="1346" alt="image" src="https://github.com/tmforum-oda/oda-canvas/assets/4638097/949b8b5f-a059-4331-b1d6-bdae18510bba">

**Comment by LesterThomas** [comment]
You are correct that the Kind should be CamelCase. (The `PublishedNotification` and `SubscribedNotification` have already adopted this convention, but the `component` and `api` CRDs have not). I assume we change the components and api custom resource definition to:

```
  names:
    plural: "components"
    singular: "component"
    kind: "Component"
```

and 

```
  names:
    plural: "apis"
    singular: "api"
    kind: "API"
```
