### ISSUE TITLE
Add release, contribution and code of conduct

### ISSUE THREAD

**Issue by brian-burton** [tmforum-oda/oda-canvas#249]
## Add release, contribution and code of conduct guidelines

As per the ODA Code Governance meeting on 6 June 2024, we need to add guidance on Release management, contributing and a code of conduct.

The proposal is:
- Release management based on [SemVer 2.0.0](https://semver.org/spec/v2.0.0.html) and [Trunk Based Development](https://trunkbaseddevelopment.com/)
- Contributor guidelines depending on [how we want to encourage contributions](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
- A [code of conduct](https://opensource.guide/code-of-conduct/) based on existing templates like the [Contributor Covenant](https://www.contributor-covenant.org/)

**Comment by ferenc-hechler** [comment]
Some thoughts about building/versioning/releasing of Dockerfiles.

Releases from the master branch have a fixed version number "<n>.<n>.<n>".
Prereleases from the feature branches have a prerelease number "<n>.<n>.<n>-<prerelease>".

Following [SemVer 2.0.0](https://semver.org/spec/v2.0.0.html) the ordering of a number with prerelease is before the version number without prerelease. E.g. "1.0.0-odaa26" < "1.0.0"

The versions for all dockerfiles should be stored only once at one central place.
We can use the values.yaml file to store the current version number of a dockerfile.
To make it better accessible, the image value ("ocfork/secretsmanagement-operator:0.1.0/odaa-26") can be split into three parts:

```
secretsmanagement-operator:
  image: ocfork/secretsmanagement-operator
  version: 0.1.0
  prereleaseSuffix: odaa-26
```

In the feature branches the prereleaseSuffix has to be set to a value, while in the master branch it has to be unset.
There can be an automation, if in the project settings, the "Workflow permissions" are set to "Read and write permissions".
So, when merging a PR, the prereleaseSuffix could be automatically removed.

For the SecretsManagement-Operator and -Sidecar I added workflows for building the dockerimages based on the values.yaml and also check, whether the branch type matches the configured version number:

https://github.com/ODA-CANVAS-FORK/oda-canvas-component-vault/blob/odaa-26-ghactions/.github/workflows/build-prerelease-secretsmanagement-operator.yml

```
name: Build SecretsManagement-Operator Prerelease Dockerimage
on: 
  push:
    branches:
    - feature/*
    paths:
    - source/operators/secretsmanagementOperator-hc/docker/**/*
jobs:
  build-secrets-management-operator-prerelease-dockerfile-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: read image of secretsmanagement-operator from values.yaml
        id: get_smanop_image
        uses: mikefarah/yq@master
        with:
          cmd: yq '.secretsmanagement-operator.image' charts/canvas-oda/values.yaml
      - name: read versionnumber of secretsmanagement-operator from values.yaml
        id: get_smanop_version
        uses: mikefarah/yq@master
        with:
          cmd: yq '[.secretsmanagement-operator.version, .secretsmanagement-operator.prereleaseSuffix] | filter(.!=null and .!="") | join("-")' charts/canvas-oda/values.yaml
      - name: Check Version
        id: check-tag
        run: |
          echo 
          if [[ ${{ steps.get_smanop_version.outputs.result }} =~ ^[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
              echo "Version ${{ steps.get_smanop_version.outputs.result }} matches featurebranch format <n>.<n>.<n>-<prerelease>"
          else
              echo "::error::Version ${{ steps.get_smanop_version.outputs.result }} does not matche featurebranch format <n>.<n>.<n>-<prerelease>" && exit 1
          fi        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: source/operators/secretsmanagementOperator-hc/docker
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.get_smanop_image.outputs.result }}:${{ steps.get_smanop_version.outputs.result }}
```

So, the process could look like the following:

1. Create a Branch feature/odaa-123
2. Edit the values.yaml for each Dockerfile xxx, which should be modified in the branch
2.1. increment xxx.version
2.2. set xxx.prereleaseSuffix to odaa-123
4. Modify the sources
4.1. If sources are modified, without having the prereleaseSuffix set, the Action will raise an error
5. create a PR
6. TBD: unset the xxx.prereleaseSuffix in values.yaml. Either via Action or manually
7. Merge PR
7.1. If xxx.prereleaseSuffix was not unset, the GitHub Action will raise an error

This way, deploying the charts from the branches allways contains runnable images and never can overwrite a release version.
