### ISSUE TITLE
1Beta4 Schema Issue

### ISSUE THREAD

**Issue by hvaughanattmforum** [tmforum-oda/oda-canvas#262]
Please add the ask in TAC 909 to the next upgrade of the YAML Schema.

TAC-909	Update component template: add frameworks (sid, eTOM, FF)

**Comment by LesterThomas** [comment]
Including details from https://projects.tmforum.org/jira/browse/TAC-909

Enhance Component yaml template as follows:

 

 

Metadata: add Framework version as just introduced into the Functional Specification:
eTom
SID
functionalFramework
Evaluate new block for content around:
eTom
SID
functionalFramework

**Comment by LesterThomas** [comment]
We will put these in a block called `componentMetadata`

**Comment by LesterThomas** [comment]
An example for `TMFC028` Party Management Component will look like:

```yaml
componentMetadata:
  eTom:
  - 1.7.7:
  - 1.7.7.2
  - 1.3.4.4
  SID:
  - Party:
    - Party
    - Contact Medium
    - Currency and tax exemption certificates
  functionalFramework:
  - 369
  - 225
  - 400
  - 282
  ```

**Comment by LesterThomas** [comment]
I've added `componentMetadata` to feature branch. It looks like:

```yaml
              componentMetadata:
                type: object
                properties:
                  id:
                    type: string
                    description: This is the id of functional component and must refer to the id of a TM Forum published golden component.
                    example: TMFC001
                  name:
                    type: string
                    description: This is the name of functional component and must refer to the name of a TM Forum published golden component.
                    example: ProductCatalogManagement
                  version:
                    type: string
                    description: This is the version of the component (it is specific to the vendor of this component and not the type).
                  description:
                    type: string
                    description: This is a short description of the component's purpose.
                  functionalBlock:   
                    type: string
                    description: This is the functional block of the component with the Open Digital Architecture.
                    example: CoreCommerce 
                  publicationDate:
                    type: string
                    format: date-time
                    description: This is the date that the golden component was published.
                  status:
                    type: string
                    description: This is the status of the golden component.
                  eTom:
                    type: array
                    description: This is the eTom mapping of the component with the Open Digital Architecture.
                    items:
                      type: string
                  SID:
                    type: array
                    description: This is the SID mapping of the component with the Open Digital Architecture.
                    items:
                      type: string
                  functionalFramework:
                    type: array
                    description: This is the functional framework of the component with the Open Digital Architecture.   
                    items:
                      type: string 
                  maintainers:
                    type: array
                    description: Maintainers is an optional list of maintainers of
                      the component. The maintainers in this list maintain the the
                      source code, images, and package for the component.
                    items:
                      description: ContactData contains information about an individual or organization.
                      type: object
                      properties:
                        email:
                          description: Email is the email address.
                          type: string
                        name:
                          description: Name is the descriptive name.
                          type: string
                        url:
                          description: Website address of maintaining organization.
                          type: string
                  owners:
                    type: array
                    description: Owners is an optional list of the owners of the installed component.
                    items:
                      type: object
                      description: ContactData contains information about an individual or organization.
                      properties:
                        email:
                          description: Email is the email address.
                          type: string
                        name:
                          description: Name is the descriptive name.
                          type: string
                        url:
                          description: Website address of owning organization.
                          type: string
                          
```

eTom, SID and Functional Framework are just arrays of strings that should refer to the relevant framework.
