### ISSUE TITLE
operator: Kong and APIGee operator installation and configuration

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#321]
## Description

This issue proposes some changes to the installation for when we include API Gateway ingress options. These are the changes from a Canvas using Istio to control API access (with no API Gateway), to using an API Gateway on top of Istio.

The default configuration for Istio is to configure `VirtualService` resources for each API that creates a route to a `Gateway`. Here are the `VirtualService` resources for the ProductCatalog example component:

 
![image](https://github.com/user-attachments/assets/53ce6282-97e3-4d7c-868f-3463f3b292a3)

When there no API Gateway, you need to create an `Gateway` called `component-gateway` that points to an `Ingress` Service. If there is an API Gateway, you should create a `Gateway` that points to the API Gateway ingress proxy.

The current setup is to install the Canvas which installs the Istio Gateway with no API Gateway, and then optionally install either the Kong or Apigee API Gateways. The API Gateway charts overwrite the default Istio config. This has two issues:

* You can still call the APIs via the Istio Gateway (bypassing the API Gateway).
* If we upgrade the Canvas, it will overwrite the API Gateway config. You would have to manually ensure to re-apply the API Gateway charts after upgrading the Canvas.

The API Gateway configurations should still use the Service Mesh (so that components need explicit permission to call other components), but the Service Mesh should link the components to the API Gateway.

I propose that we change the installation and make the Istio / Kong-Istio / Apigee-Istio configurations peers of each other. The installation will install the base Canvas with no ingress mechanism, and then you install one-of Istio / Kong-Istio / Apigee-Istio charts.

**Comment by brian-burton** [comment]
This is a good idea. So we'd have to:
- change the default reference canvas installation to remove Istio Ingress (but leave the Istio Service Mesh prerequisite in place)
- document Istio Ingress, Kong, Apigee and Apisix installations and specify that you must pick one of them to make a working reference canvas.

I think this should be easy to do, and could set a pattern for how a canvas service marketplace would work (e.g. how to take out the Keycloak identity configuration operator and replace with a different identiy platform).

**Comment by LesterThomas** [comment]
Here is some guidance from ChatGPT on how to integrate **Istio Service Mesh** and **Kong API Gateway**.

To integrate **Istio Service Mesh** and **Kong API Gateway** with `VirtualService` resources, you would need a setup where the **Kong API Gateway** acts as the external API gateway, handling external requests, and then forwards traffic to services inside the Istio service mesh. This allows Kong to manage features like authentication, rate limiting, and request/response transformations, while Istio handles the service mesh, traffic routing, and observability inside the cluster.

### Architecture Overview:

1. **Kong API Gateway**: Exposes external-facing APIs, handles incoming requests, and forwards traffic to the Istio ingress gateway or directly to services inside the mesh.
2. **Istio Ingress Gateway**: Handles traffic from Kong and forwards it to the appropriate services using Istio’s `VirtualService` for internal routing.
3. **Istio VirtualService**: Manages traffic routing within the mesh, from the ingress gateway to the destination services.

### Setup Steps and Example Configuration:

#### 1. **Kong API Gateway Configuration**

Kong will be the external entry point for your APIs. You can deploy Kong in the same Kubernetes cluster, configure it to manage incoming traffic, and use Kong’s routing mechanisms to forward requests to the Istio ingress gateway or services within the mesh.

Here’s an example of how Kong would be configured to route traffic to Istio’s ingress gateway.

```yaml
apiVersion: configuration.konghq.com/v1
kind: Ingress
metadata:
  name: kong-ingress
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/https-redirect-status-code: "301"
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /service
            backend:
              serviceName: istio-ingressgateway  # Istio ingress gateway service
              servicePort: 80
```

In this configuration:
- Kong listens on `api.example.com/service`.
- Requests are forwarded to Istio’s ingress gateway service (`istio-ingressgateway`), which will handle traffic inside the mesh.

#### 2. **Istio Ingress Gateway Configuration**

Once traffic reaches the Istio ingress gateway from Kong, Istio handles routing within the mesh. You need to configure a `Gateway` and a `VirtualService` to manage this traffic.

Here’s an example Istio `Gateway` configuration:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway  # Use the Istio ingress gateway pod for this Gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "api.example.com"  # Hostname matches the one defined in Kong
```

This `Gateway` listens for traffic on port 80 for the host `api.example.com`, which matches the traffic coming from Kong.

#### 3. **Istio VirtualService for Routing**

Once the traffic hits the Istio ingress gateway, the `VirtualService` will define how traffic is routed to services inside the mesh.

Here’s an example of a `VirtualService`:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-routing
  namespace: istio-system
spec:
  hosts:
    - "api.example.com"  # Matches the Gateway's host and Kong's domain
  gateways:
    - istio-gateway       # Reference to the Gateway resource
  http:
    - match:
        - uri:
            prefix: "/service"
      route:
        - destination:
            host: my-service  # Kubernetes service name for the destination
            port:
              number: 8080     # Port exposed by the destination service
```

In this `VirtualService` configuration:
- The `hosts` field matches the traffic coming from Kong (`api.example.com`).
- The `gateways` field references the Istio `Gateway` defined earlier.
- The `http.match` section defines that requests matching `/service` should be routed to the `my-service` service in the mesh.
- The traffic is forwarded to `my-service` on port `8080`.

### Summary of Flow:

1. **Kong API Gateway**: External clients access `api.example.com/service` through Kong.
   - Kong forwards traffic to the Istio ingress gateway.
   
2. **Istio Gateway**: Istio’s ingress gateway receives traffic from Kong on port 80 for `api.example.com`.
   - The Istio Gateway directs traffic into the mesh, where it is handled by Istio’s routing logic.

3. **Istio VirtualService**: Based on the routing rules defined in the `VirtualService`, Istio forwards traffic to the appropriate service (`my-service`) inside the mesh.

### Additional Considerations:

1. **Kong Plugins**: You can configure Kong plugins for rate limiting, authentication, logging, etc., on top of this setup. Kong will handle these aspects before the traffic reaches Istio.

2. **MTLS**: If you want mutual TLS (mTLS) between Kong and the Istio ingress gateway, you’ll need to configure both Kong and Istio for mTLS.

3. **Service Mesh Benefits**: Once traffic enters the Istio service mesh, you can take advantage of all Istio features like traffic management (canary deployments, fault injection, retries), security (mTLS), and observability (tracing, metrics).

4. **Cross-Namespace Communication**: Make sure that the `Gateway` and `VirtualService` are defined in the appropriate namespace and that cross-namespace communication is configured correctly if services span multiple namespaces.

### Conclusion:

By combining **Kong API Gateway** with **Istio**:
- **Kong** can manage external API traffic with features like authentication and rate limiting.
- **Istio** can manage internal traffic routing and provide additional benefits like traffic control, security, and observability inside the mesh.
- The integration is achieved by configuring Kong to forward traffic to the Istio ingress gateway, which then routes traffic to services using Istio’s `VirtualService` resources.

**Comment by LesterThomas** [comment]
Here is some guidance from ChatGPT on how to integrate **Istio Service Mesh** and **Kong API Gateway**.

To integrate **Istio Service Mesh** and **Kong API Gateway** with `VirtualService` resources, you would need a setup where the **Kong API Gateway** acts as the external API gateway, handling external requests, and then forwards traffic to services inside the Istio service mesh. This allows Kong to manage features like authentication, rate limiting, and request/response transformations, while Istio handles the service mesh, traffic routing, and observability inside the cluster.

### Architecture Overview:

1. **Kong API Gateway**: Exposes external-facing APIs, handles incoming requests, and forwards traffic to the Istio ingress gateway or directly to services inside the mesh.
2. **Istio Ingress Gateway**: Handles traffic from Kong and forwards it to the appropriate services using Istio’s `VirtualService` for internal routing.
3. **Istio VirtualService**: Manages traffic routing within the mesh, from the ingress gateway to the destination services.

### Setup Steps and Example Configuration:

#### 1. **Kong API Gateway Configuration**

Kong will be the external entry point for your APIs. You can deploy Kong in the same Kubernetes cluster, configure it to manage incoming traffic, and use Kong’s routing mechanisms to forward requests to the Istio ingress gateway or services within the mesh.

Here’s an example of how Kong would be configured to route traffic to Istio’s ingress gateway.

```yaml
apiVersion: configuration.konghq.com/v1
kind: Ingress
metadata:
  name: kong-ingress
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/https-redirect-status-code: "301"
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /service
            backend:
              serviceName: istio-ingressgateway  # Istio ingress gateway service
              servicePort: 80
```

In this configuration:
- Kong listens on `api.example.com/service`.
- Requests are forwarded to Istio’s ingress gateway service (`istio-ingressgateway`), which will handle traffic inside the mesh.

#### 2. **Istio Ingress Gateway Configuration**

Once traffic reaches the Istio ingress gateway from Kong, Istio handles routing within the mesh. You need to configure a `Gateway` and a `VirtualService` to manage this traffic.

Here’s an example Istio `Gateway` configuration:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway  # Use the Istio ingress gateway pod for this Gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "api.example.com"  # Hostname matches the one defined in Kong
```

This `Gateway` listens for traffic on port 80 for the host `api.example.com`, which matches the traffic coming from Kong.

#### 3. **Istio VirtualService for Routing**

Once the traffic hits the Istio ingress gateway, the `VirtualService` will define how traffic is routed to services inside the mesh.

Here’s an example of a `VirtualService`:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-routing
  namespace: istio-system
spec:
  hosts:
    - "api.example.com"  # Matches the Gateway's host and Kong's domain
  gateways:
    - istio-gateway       # Reference to the Gateway resource
  http:
    - match:
        - uri:
            prefix: "/service"
      route:
        - destination:
            host: my-service  # Kubernetes service name for the destination
            port:
              number: 8080     # Port exposed by the destination service
```

In this `VirtualService` configuration:
- The `hosts` field matches the traffic coming from Kong (`api.example.com`).
- The `gateways` field references the Istio `Gateway` defined earlier.
- The `http.match` section defines that requests matching `/service` should be routed to the `my-service` service in the mesh.
- The traffic is forwarded to `my-service` on port `8080`.

### Summary of Flow:

1. **Kong API Gateway**: External clients access `api.example.com/service` through Kong.
   - Kong forwards traffic to the Istio ingress gateway.
   
2. **Istio Gateway**: Istio’s ingress gateway receives traffic from Kong on port 80 for `api.example.com`.
   - The Istio Gateway directs traffic into the mesh, where it is handled by Istio’s routing logic.

3. **Istio VirtualService**: Based on the routing rules defined in the `VirtualService`, Istio forwards traffic to the appropriate service (`my-service`) inside the mesh.

### Additional Considerations:

1. **Kong Plugins**: You can configure Kong plugins for rate limiting, authentication, logging, etc., on top of this setup. Kong will handle these aspects before the traffic reaches Istio.

2. **MTLS**: If you want mutual TLS (mTLS) between Kong and the Istio ingress gateway, you’ll need to configure both Kong and Istio for mTLS.

3. **Service Mesh Benefits**: Once traffic enters the Istio service mesh, you can take advantage of all Istio features like traffic management (canary deployments, fault injection, retries), security (mTLS), and observability (tracing, metrics).

4. **Cross-Namespace Communication**: Make sure that the `Gateway` and `VirtualService` are defined in the appropriate namespace and that cross-namespace communication is configured correctly if services span multiple namespaces.

### Conclusion:

By combining **Kong API Gateway** with **Istio**:
- **Kong** can manage external API traffic with features like authentication and rate limiting.
- **Istio** can manage internal traffic routing and provide additional benefits like traffic control, security, and observability inside the mesh.
- The integration is achieved by configuring Kong to forward traffic to the Istio ingress gateway, which then routes traffic to services using Istio’s `VirtualService` resources.
