### ISSUE TITLE
Canvas: implement support for forward proxies

### ISSUE THREAD

**Issue by ycardon-pro** [tmforum-oda/oda-canvas#33]
## long story short

In Orange current deployments, k8s cluster where the canvas is deployed do not have direct access to internet, all outgoing access pass through a forward proxy that have to be configured at the cluster level but also inside each payload.

This proxy support feature is available for most of the products we use on the cluster but the documentation / helm charts of the canvas does not seem to state anything about it.

## potential problems and attempts to bypass them

- the `specification` of `exposedAPIs` of a `component` CRD might be fetched from internet 

> setting some environment variables in the deployment chart of the `oda-controller-ingress` deployment does not seems to be taken in account

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oda-controller-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oda-controller-ingress
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: oda-controller-ingress
        {{- include "controller.labels" . | nindent 8 }}
    spec:
      serviceAccountName: odacomponent-account
      containers:
      - name: oda-controller-ingress
        image: {{.Values.deployment.compconimage}}
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          - secretRef:
              name: {{ .Release.Name }}-secret

# proxy conf
        env:
        - name: "HTTP_PROXY"
          value: "http://xxx:3128"
        - name: "HTTPS_PROXY"
          value: "http://xxx:3128"
        - name: "NO_PROXY"
          value: "no_proxy=localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,cattle-system.svc,.svc,.cluster.local"
# end proxy conf

      - name: seccon
        image: {{.Values.deployment.secconimage}}
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          - secretRef:
              name: {{ .Release.Name }}-secret
        ports:
        - name: seccon
          containerPort: 5000
```
