### ISSUE TITLE
Authentication: Adding authentication to outbound API calls from Component

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#362]
## Description

For outbound calls from a Component (to another component or to an external API), we want to use Auth 2.0 Client Credentials Flow. The component needs to use its ClientID/Secret to get a token from IDM OAuth 2.0 gateway. It then calls the outbound API with the token. The target of the API call can use the token to understand who is calling and with what Role.

We have several options:

1. Leave it for every component to implement this process; We would need to somehow share the ClientID/Secret with the component using a Kubernetes secret or secrets vault.
2. We could provide a set of language-specific libraries to help a component implement this process. 
3. We could use a sidecar to offload the process from the component. This could be either adding additional functionality to the current Istio service mesh component, or developing a new sidecar specifically for this process.

From Mumbai workshop and discussions with @brian-burton and @ferenc-hechler we recommend some additional research around these options. If we could add this into the existing Istio sidecar using an Envoy Filter or similar (see [Envoy Filter for OAuth](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter )) then this could be the preferred solution. If not, then there were concerns about creating too-many sidecars.

To communicate the ClientID/Secret to the component (or sidecar) this could be shared as a Kubernetes secret generated by the Identity Operator, or by adding to the Secrets Vault.

**Comment by ferenc-hechler** [comment]
Started to setup a test scenario for OAuth2 with KeyCloak.

First I installed a component from the testdata:

```
helm upgrade --install ctk -n components feature-definition-and-test-kit/testData/productcatalog-v1beta4
```

Looking in KeyCloak I can see that a client `ctk-productcatalogmanagement` was created:

![image](https://github.com/user-attachments/assets/d86fda24-63d8-4335-b9df-9f4094a0f695)

Client-ID and Client-Secret can be found in the Client-Details > Credentials:

![image](https://github.com/user-attachments/assets/b06b57f0-ba78-4864-8dd9-1391e4b0fdf8)

The open-ID endpoints can be found in the Realm-Settings:

![image](https://github.com/user-attachments/assets/62eb1a1a-c0a2-480c-9211-5481f725f06a)

The link directs to the .well-known/openid-configuration of the myrealm:

![image](https://github.com/user-attachments/assets/bd280ace-7355-4b86-aecc-37b59a39edf1)

So, now I have the following required information:

```
Client-ID: ctk-productcatalogmanagement
Client-Secret: wTju...vc1B
Token-Access-Endpoint: https://canvas-keycloak.ihc-dt.cluster-3.de/auth/realms/myrealm/protocol/openid-connect/token
```

I configured authentication in Postman with these values:

![image](https://github.com/user-attachments/assets/d0ca01bf-fe5d-4436-a925-f16b87c0053e)

But when trying to retrieve a token an error message is returned:

![image](https://github.com/user-attachments/assets/1ea1aa43-a1bc-490c-be81-834b7ea739f6)

After some internet research I found, that service accounts have to be enabled in the client settings:

![image](https://github.com/user-attachments/assets/eab0ea19-bca9-44bb-97ae-fff0c4ba3e32)

Now Postman is happy :-)

![image](https://github.com/user-attachments/assets/4ccbe780-77d3-4dba-9d16-2f451bff1f59)

The Payload of the returned JWT:

```
{
    "exp": 1732177421,
    "iat": 1732177121,
    "jti": "194cf4c4-9c1e-4172-9fec-bbab0567b44c",
    "iss": "https://canvas-keycloak.ihc-dt.cluster-3.de/auth/realms/myrealm",
    "aud": "account",
    "sub": "93b2aa50-856d-41ad-b5d0-91012796dbbb",
    "typ": "Bearer",
    "azp": "ctk-productcatalogmanagement",
    "acr": "1",
    "realm_access": {
        "roles": [
            "default-roles-myrealm",
            "offline_access",
            "uma_authorization"
        ]
    },
    "resource_access": {
        "account": {
            "roles": [
                "manage-account",
                "manage-account-links",
                "view-profile"
            ]
        }
    },
    "scope": "profile email",
    "clientHost": "10.88.3.1",
    "email_verified": false,
    "clientId": "ctk-productcatalogmanagement",
    "preferred_username": "service-account-ctk-productcatalogmanagement",
    "clientAddress": "10.88.3.1"
}
```

**Comment by ferenc-hechler** [comment]
So, what Postman is doing is to add the JWT as Bearer Authorization to the request (line 2):

```
GET /service HTTP/1.1
Authorization: Bearer eyJh...q1RA
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Postman-Token: 844143bf-9ee1-43ff-ad02-83c4cc26ff31
Host: canvas-info.ihc-dt.cluster-3.de
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```

What we want to achieve is, that an Envoy filter is doing the same, get a token, add it to all outgoing requests and refresh the token after some time.

**Comment by ferenc-hechler** [comment]
There is a prototype extension which seems to be doing what we intend to do:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/injected_credentials/oauth2/v3/oauth2.proto.html

![image](https://github.com/user-attachments/assets/ca904f64-2e71-4116-ab76-5dab6541ed80)

**Comment by LesterThomas** [comment]
> After some internet research I found, that service accounts have to be enabled in the client settings

Do we need to add this to the identity config operator so that this happens automatically?

**Comment by ferenc-hechler** [comment]
To be able to retrieve a token I needed this. 
Maybe there are other ways for token retrieval and I did it the wrong way. 
But If this is the way, then we have to add it to ConfigOperator.

**Comment by ferenc-hechler** [comment]
Successfully injected an OAuth2 token for inbound calls through the component Gateway.
(That is not the goal, it should be outbound later)

Envoy has a Secrets-Discovery-Service (SDS). We have to bring the client-secret into the Envoy secrets.
To do this, secrets can be defined from filesystem. And in K8S the Filesystem can be mounted from a ConfigMap or Secret.



```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: istio-ingress
  name: oauth2secs-cm
data:
  demo-a-productcatalogmanagement.yaml: |+
    resources:
    - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
      name: clientsecret
      generic_secret:
        secret:
          # Fill in the client secret your OAuth2 provider assigned to you.
          inline_bytes: "ZGVq...RLTUo"
```

We are doing this in the istio-ingress namespace as we first try to patch incoming requests.

**Comment by ferenc-hechler** [comment]
Now we can define the EnvoyFilter for injecting the secrets:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoyfilter-oauth2-test
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
    patch:
      operation: INSERT_BEFORE
      value: 
         # https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/credential_injector_filter#oauth2-credential-injector-client-credential-grant
         # (https://github.com/veehaitch/envoy-oauth2-filter-google/blob/main/envoy/envoy.yaml)
         name: envoy.filters.http.credential_injector
         typed_config:
             "@type": type.googleapis.com/envoy.extensions.filters.http.credential_injector.v3.CredentialInjector
             credential:
               name: envoy.http.injected_credentials.oauth2
               typed_config:
                 "@type": type.googleapis.com/envoy.extensions.http.injected_credentials.oauth2.v3.OAuth2
                 token_endpoint:
                   cluster: "outbound|8083||canvas-keycloak.canvas.svc.cluster.local"
                   timeout: 3s
                   uri: "http://canvas-keycloak.canvas.svc.cluster.local/auth/realms/myrealm/protocol/openid-connect/token"
                 client_credentials:
                   client_id: demo-a-productcatalogmanagement
                   client_secret:
                     name: clientsecret
                     sds_config:
                       path_config_source:
                         path: "/config_map/oauth2secs/demo-a-productcatalogmanagement.yaml"
                         watched_directory: 
                            path: "/config_map/oauth2secs"
```

Requests to the echoservice now have an injected Authorization Bearer:

![image](https://github.com/user-attachments/assets/90cf532b-e221-49ee-b882-209188642713)

Pasting the authorization token into a JWT parser retrieves the following payload:

```
{
    "exp": 1732536866,
    "iat": 1732536566,
    "jti": "0548dfa9-ace6-49f3-9e00-b58e7a9a90ce",
    "iss": "http://canvas-keycloak.canvas.svc.cluster.local/auth/realms/myrealm",
    "aud": "account",
    "sub": "0ce4c44d-b977-4023-8d95-94e7954a3d09",
    "typ": "Bearer",
    "azp": "demo-a-productcatalogmanagement",
    "acr": "1",
    "realm_access": {
        "roles": [
            "default-roles-myrealm",
            "offline_access",
            "uma_authorization"
        ]
    },
    "resource_access": {
        "account": {
            "roles": [
                "manage-account",
                "manage-account-links",
                "view-profile"
            ]
        }
    },
    "scope": "profile email",
    "clientId": "demo-a-productcatalogmanagement",
    "email_verified": false,
    "clientHost": "10.64.0.112",
    "preferred_username": "service-account-demo-a-productcatalogmanagement",
    "clientAddress": "10.64.0.112"
}
```

**Comment by ferenc-hechler** [comment]
Got it now working with a deployed component:

### Step1 Patch Sidecar Template

Each istio-proxy sidcar should automatically mount the optional secret `envoy-oauth2-secrets`. This allows defining secrets based on the mounted secret in the filesystem.

TODO: figure out, how to do this at install time with values.yaml

```
apiVersion: v1
data:
  config: |-
    # defaultTemplates defines the default template to use for pods that do not explicitly specify a template
    defaultTemplates: [sidecar]
    policy: enabled
    ...
    templates:
      sidecar: |
        {{- define "resources"  }}
          ...
          - name: istio-proxy
           ...
            volumeMounts:
            - name: workload-socket
              ...
[+]         # ----- MOUNTED SECRET -----
[+]         - mountPath: /envoy_secrets/oauth2secs
[+]           name: envoy-oauth2-secrets-vol
          volumes:
          - emptyDir:
            ...
[+]       # ----- SDS VOLUME ----- 
[+]       - name: envoy-oauth2-secrets-vol
[+]         secret:
[+]           optional: true
[+]           defaultMode: 420
[+]           secretName: envoy-oauth2-secrets
            
          {{- if .Values.global.imagePullSecrets }}
          imagePullSecrets:
       ...
kind: ConfigMap
metadata:
  ...
  name: istio-sidecar-injector
  namespace: istio-system
```

### Step 2 Create Secret 

create a secret which contains the credentials (client_secrets) for all components in the namespace.

`envoy-oauth2-secrets/demo-a-productcatalogmanagement.yaml:`

```
resources:
- "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
  name: clientsecret
  generic_secret:
    secret:
      inline_string: "oQH2khKfbC7QPBJTFXDMTGmesH5UpQY0"
```

(alternative to inline_string is inline_bytes with base64 encoding)

```
kubectl create secret -n components generic envoy-oauth2-secrets --from-file=envoy-oauth2-secrets --dry-run=client -o yaml | kubectl apply -f -
```

STEP 3: Create EnvoyFilter for OAuth2 injection

The workload is selected based on labels. 
Here we select `app=demo-a-productcatalogmanagement`

The client_secret is defined using `sds_config.path_config_source` to the mounted secret.
The watcher monitors updates on the secret with a few seconds delay.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoyfilter-oauth2-curlpod
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: demo-a-productcatalogmanagement
  configPatches:
  # https://github.com/istio/istio/issues/47572
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: INSERT_BEFORE
      value: 
         # https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/credential_injector_filter#oauth2-credential-injector-client-credential-grant
         # (https://github.com/veehaitch/envoy-oauth2-filter-google/blob/main/envoy/envoy.yaml)
         # name: envoy.filters.http.oauth2
         name: envoy.filters.http.credential_injector
         typed_config:
             "@type": type.googleapis.com/envoy.extensions.filters.http.credential_injector.v3.CredentialInjector
             credential:
               name: envoy.http.injected_credentials.oauth2
               typed_config:
                 "@type": type.googleapis.com/envoy.extensions.http.injected_credentials.oauth2.v3.OAuth2
                 token_endpoint:
                   cluster: "outbound|8083||canvas-keycloak.canvas.svc.cluster.local"
                   timeout: 3s
                   uri: "http://canvas-keycloak.canvas.svc.cluster.local:8083/auth/realms/myrealm/protocol/openid-connect/token"
                 client_credentials:
                   client_id: demo-a-productcatalogmanagement
                   client_secret:
                     name: clientsecret
                     sds_config:
                       path_config_source:
                         path: "/envoy_secrets/oauth2secs/demo-a-productcatalogmanagement.yaml"
                         watched_directory: 
                            path: "/envoy_secrets/oauth2secs"
```

Now we can test this by logging into the prodcatapi-pod:

```
$ kubectl exec -n components demo-a-prodcatapi-75d6b7577f-n22t6 -it -- /bin/bash

root@demo-a-prodcatapi-75d6b7577f-n22t6:/src# curl http://echoservice.echoservice.svc.cluster.local/ip

<h3 style="background-color: green;">log request ip infos</h3><b>client-ip:</b> 127.0.0.6<br><b>header:</b><br><pre><code>Host: echoservice.echoservice.svc.cluster.local
User-Agent: curl/7.64.0
Accept: */*
X-Forwarded-Proto: http
X-Request-Id: f18b8039-d16e-4e05-829c-51544c8a0239
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2VkRxRmRIX1dDSTRCYXNMZGhlZWRTNERlbjZXWGtwX25zcVZ6ZExsVUVFIn0.eyJleHAiOjE3MzI2MzYxNzQsImlhdCI6MTczMjYzNTg3NCwianRpIjoiNDIzMjNmNDEtMmYyNy00NTIwLWI5MGItZTNkMTNlYWFiYjViIiwiaXNzIjoiaHR0cDovL2NhbnZhcy1rZXljbG9hay5jYW52YXMuc3ZjLmNsdXN0ZXIubG9jYWw6ODA4My9hdXRoL3JlYWxtcy9teXJlYWxtIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImExOTZjNGYxLTkxYzUtNDk4YS04ZmRjLWU3OTJhMTdjMWExMSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImRlbW8tYS1wcm9kdWN0Y2F0YWxvZ21hbmFnZW1lbnQiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbXlyZWFsbSIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJjbGllbnRIb3N0IjoiMTAuMTYuMC45OCIsImNsaWVudElkIjoiZGVtby1hLXByb2R1Y3RjYXRhbG9nbWFuYWdlbWVudCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LWRlbW8tYS1wcm9kdWN0Y2F0YWxvZ21hbmFnZW1lbnQiLCJjbGllbnRBZGRyZXNzIjoiMTAuMTYuMC45OCJ9.cFUmD4-jIBeuMVjIf8M2rId0EwD7MSopKvub4yQ_ssV_afWpzHHAnx9Ablf_5BlPM-gIsWeyprdSfRaoXacRadrsmXU-Bkf_MabvuCDFMzZyO4KRNM7KKhTcKOxBqfSg0wWlFugLzVefzbMNe36yLo7es2GZnIXU4xBRk3GuKboVuwx-uRJ3vNZX7VQvkmogbMjoN2S4Jaf0XgGGMc7IotYIiOcsqbMWpm1NzQjoDi_KECvVluTeXZDb6YHvda6LlPqes07fFToyO3mXLVgIf6ytInEeeu56DGh3o1NtJNb3zz8gqQ47JqU5vWma_L5IUR9KdFiUcpiKY3YO5b4gRQ
X-Envoy-Attempt-Count: 1
X-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/echoservice/sa/default;Hash=cc12ec6e29a6e7c9d2dfcc11199ff037f1446a59d921ef9482a75ea1a0b5afb1;Subject="";URI=spiffe://cluster.local/ns/components/sa/default

</code></pre><ul><li><a href='/'>ROOT</a><li><a href='/hello'>hello</a><li><a href='/ip'>ip</a></ul>
```

The authorization bearer was automatically injected.

**Comment by ferenc-hechler** [comment]
The HTTP->HTTPS switch can be done using [Egress TLS Origination](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-tls-origination/).

An example for one target domain looks like this:

```
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  namespace: components
  name: echo-free-beeceptor-com
spec:
  hosts:
  - echo.free.beeceptor.com
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
    targetPort: 443
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  namespace: components
  name: echo-free-beeceptor-com
spec:
  host: echo.free.beeceptor.com
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      tls:
        mode: SIMPLE # initiates HTTPS when accessing echo.free.beeceptor.com
```

Testing the same request as above:

```
root@demo-a-prodcatapi-75d6b7577f-n22t6:/src# curl http://echo.free.beeceptor.com
{
  "method": "GET",
  "protocol": "https",
  "host": "echo.free.beeceptor.com",
  ..."path": "/",
  "ip": "35.240.55.139:44352",
  "headers": {
    "Host": "echo.free.beeceptor.com",
    ...
    "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2VkRxRmRIX1dDSTRCYXNMZGhlZWRTNERlbjZXWGtwX25zcVZ6ZExsVUVFIn0.eyJleHAiOjE3MzI2NjAzODQsImlhdCI6MTczMjY2MDA4NCwianRpIjoiY2VmMDRkNmEtNTA5Yi00MGU0LTlmMzEtZGQ3YjM5ZDZlZmI4IiwiaXNzIjoiaHR0cDovL2NhbnZhcy1rZXljbG9hay5jYW52YXMuc3ZjLmNsdXN0ZXIubG9jYWw6ODA4My9hdXRoL3JlYWxtcy9teXJlYWxtIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImExOTZjNGYxLTkxYzUtNDk4YS04ZmRjLWU3OTJhMTdjMWExMSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImRlbW8tYS1wcm9kdWN0Y2F0YWxvZ21hbmFnZW1lbnQiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtbXlyZWFsbSIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJjbGllbnRIb3N0IjoiMTAuMTYuMC45OCIsImNsaWVudElkIjoiZGVtby1hLXByb2R1Y3RjYXRhbG9nbWFuYWdlbWVudCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LWRlbW8tYS1wcm9kdWN0Y2F0YWxvZ21hbmFnZW1lbnQiLCJjbGllbnRBZGRyZXNzIjoiMTAuMTYuMC45OCJ9.RiJpS-rG_wOZvsOGoQz0xMS3jJ8murf-j7fEf3K8QlAjaCOxIvVUGyHTc9LisSVE0-8ZNDN6rb0psQIuzNC4bT7OfG9Lz-H_-GX_S5Go5_pOx2Z09vXtso1etmuNFcmuzkLTFpSWcEIbLNaBqJd9Hklysq23yjLnjKKAa6K5f5J-1FFPmtKLiJHntUN8z8dyQuigG4VAXx0ieRRXLUjyPwA9yhbzljGkzvQUl202lYL218iXYLlC4Rflms3oNYqx0AGwVrj7poRv3j-tmN4yTOC3OhoeN7ZxTv2MlQH1ddO1OEr8pC1HtsVvX3wnGDI_rBi0vcv91GQ_WQBfBoR18g",
    ...
  },
  "parsedQueryParams": {}
}
```

The important part is   `"protocol": "https"`.
This means the request was sent out with htpps.

For a more advanced solution it might be necessary to setup an egress gateway which then is doing the TLS origination:
https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/

**Comment by ferenc-hechler** [comment]
For managing the secrets in Kubernetes there is an alternative to use an SDS server:
https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret

```
The most important benefit of SDS is to simplify the certificate management. 
Without this feature, in k8s deployment, certificates must be 

    created as secrets and mounted into the proxy containers. 

If certificates are expired, the secrets need to be updated and 
the proxy containers need to be re-deployed. 
With SDS, a central SDS server will push certificates to all Envoy instances.
```

Hopefully this can also be used for generic secrets and not only for TLS certs.

**Comment by adawalli** [comment]
Hi all - is it possible to turn up the logging around the call to `/token`?

I have tried enabling trace for all of envoy. I see upstream cluster get resolved via DNS ok. I then see the outbound request

```
[2025-02-06 17:58:55.354][1][debug][router] [source/common/router/router.cc:525] [Tags: "ConnectionId":"0","StreamId":"16947065387580332544"] cluster 'pms.ssa' match for URL '/token'
[2025-02-06 17:58:55.354][1][debug][router] [source/common/router/router.cc:750] [Tags: "ConnectionId":"0","StreamId":"16947065387580332544"] router decoding headers:
':path', '/token'
':authority', 'service-id.stg.ssa.domain.com'
':method', 'POST'
':scheme', 'http'
'content-type', 'application/x-www-form-urlencoded'
'accept', 'application/json'
'content-length', '132'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.0.230.69'
'x-envoy-expected-rq-timeout-ms', '3000'
```

I then see a 401
```
[2025-02-06 17:51:13.582][1][trace][http] [source/common/http/filter_manager.cc:905] [Tags: "ConnectionId":"0","StreamId":"11285436673043588251"] commonEncodePrefix end_stream: true, isHalfCloseEnabled: false
[2025-02-06 17:51:13.582][1][trace][router] [source/common/router/upstream_request.cc:271] [Tags: "ConnectionId":"0","StreamId":"11285436673043588251"] end_stream: true, upstream response headers:
':status', '401'
'date', 'Thu, 06 Feb 2025 17:51:13 GMT'
'content-length', '0'
'connection', 'keep-alive'
'vary', 'Origin,Access-Control-Request-Method,Access-Control-Request-Headers'
'x-content-type-options', 'nosniff'
'x-xss-protection', '0'
'cache-control', 'no-cache, no-store, max-age=0, must-revalidate'
'pragma', 'no-cache'
'expires', '0'
'strict-transport-security', 'max-age=31536000 ; includeSubDomains'
'x-frame-options', 'DENY'

[2025-02-06 17:51:13.582][1][debug][router] [source/common/router/router.cc:1551] [Tags: "ConnectionId":"0","StreamId":"11285436673043588251"] upstream headers complete: end_stream=true
```

The thing is - I don't actually see a `401` on the real upstream OAUTH2 endpoint - I don't see any request at all. I've tried turning on TCPDUMP as well, and I don't see any requests going out to the OAUTH server despite constantly seeing the `401`s. Any suggestions would be greatly appreciated.

FWIW, here is my credential_injector config
```yaml
              - name: envoy.filters.http.credential_injector
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.credential_injector.v3.CredentialInjector
                  overwrite: true
                  credential:
                    name: envoy.http.injected_credentials.oauth2
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.http.injected_credentials.oauth2.v3.OAuth2
                      token_endpoint:
                        cluster: pms.ssa
                        timeout: 3s
                        uri: "https://service-id.stg.ssa.domain.com/token"
                      scopes:
                        - scope1
                        - scope2
                      client_credentials:
                        auth_type: BASIC_AUTH
                        client_id: "REDACTED_CLIENT_ID"
                        client_secret:
                          name: oauth2_client_secret
                          sds_config:
                            path_config_source:
                              path: "/vault/secrets/token.yaml"
                            initial_fetch_timeout: 10s  # Add this line
                            resource_api_version: V3
```
and the cluster info (slightly redacted)

```yaml
      - name: pms.ssa
        connect_timeout: 3s
        type: strict_dns
        lb_policy: round_robin
        load_assignment:
          cluster_name: pms.ssa
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: service-id.stg.ssa.domain.com
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: service-id.stg.ssa.domain.com
```
