### ISSUE TITLE
tmforumodacanvas/secretsmanagement-operator imagePullBackoff - no linux/arm64 architecture available 

### ISSUE THREAD

**Issue by subhanshu-shukla-ril** [tmforum-oda/oda-canvas#378]
## Long story short

Installing canvas in minikube, after executing helm install command for canvas, it is saying error image pull.

## Description

I have followed this installation guide.
https://github.com/tmforum-oda/oda-canvas/blob/master/installation/README.md

```
helm repo add oda-canvas https://tmforum-oda.github.io/oda-canvas
helm repo update
helm install canvas oda-canvas/canvas-oda -n canvas --create-namespace 
```
</details>

<details><summary>The exact command to reproduce the issue</summary>

`helm install canvas oda-canvas/canvas-oda -n canvas --create-namespace 
`
<img width="1706" alt="image" src="https://github.com/user-attachments/assets/17218744-3ba7-4d85-b892-f1d21ecfeefa">

## Environment

* Kopf version: 
* Kubernetes version: 
          Client Version: v1.31.0
          Kustomize Version: v5.4.2
          Server Version: v1.30.0
* Python version: 3.11.6
* OS/platform: Mac OS m2 arm 64
</details>

**Comment by ferenc-hechler** [comment]
The preinstall hook needs an image which contains kubectl and curl. Because bitnami removed curl from its kubectl docker image `quay.io/appuio/oc:v4.14` is used as an alternative.

In the branch 372 I created a new baseimage "tmforumodacanvas/baseimage-kubectl-curl", but in the master branch it is still from the quay.io docker registry.

Maybe there is an issue to access other registries than docker.io from your environment?

**Comment by ferenc-hechler** [comment]
You can take a look in the status of the POD, there should be messages about the image pull issue:

```
  containerStatuses:
  - image: tmforumodacanvas/xxx:vvv
    imageID: ""
    lastState: {}
    name: code-server
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "tmforumodacanvas/xxx:vvv"
        reason: ImagePullBackOff
```
