### ISSUE TITLE
operator: Mainly simple dependent operator

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#384]
## Description

Issue #365 adds tests for the simple dependency operator which covers 'happy-path' testing for 1 dependency with 1 down-stream API.

This issue is to handle 1 dependency with multiple downstream APIs and also the scenario for what happens if a component has dependencies that aren't initially available.

**Comment by ferenc-hechler** [comment]
Proposal from my side would be to add some kind of Label-Selector logic similair to Kubernetes:
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

So, dependent-API Custom-Resource needs a new structure selector and component CR needs a new section to define labels in the SPEC (not in the Metadata).

Then it is up to the Dependent-API-Operator (or some post processing services) to resolve disambiguates based on the selectors. E.g.: 

```
dependentAPIs: 
  - name: downstreamproductcatalog 
    apiType: openapi     
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
    selector:
      unit: business-unit
      cluster: internal-2
```
