### ISSUE TITLE
crd: use openmetrics instead of prometheus for the metrics interface

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#389]
## Description

The `Component` and `ExposedAPI` CRD's include an `apiType` which is an enumeration. At present it lists the options as:

```yaml
              apiType:
                type: string
                enum:
                - openapi
                - prometheus
                description: The type of API specification. Currently only OpenAPI (swagger) and Prometheus (metrics) APIs are supported.
```

The Prometheus standard has been widely accepted as a standard for observability metrics and is now rebranded as **open metrics** (https://github.com/prometheus/OpenMetrics/blob/main/specification/OpenMetrics.md)

We should rename the CRD to `openmetrics` and update the operators, example components and feature tests to reflect this.
