### ISSUE TITLE
component: group 

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#414]
## Description

For the ExposedAPI properties that are used to configure the API Gateway - apiKeyVerification, rateLimit, quota, OASValidation, CORS, template  -  group these together as a gatewayConfiguration object to make it clearer to understand the structure of the `exposedAPI` resource.

The target component would look like:
 
``` yaml
                  exposedAPIs:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the API
                        specification:
                          type: array
                          items:
                            type: string
                            format: url
                          description: >
                            URL to the specification of the API, e.g., Swagger file.
                            Supports multiple specifications (e.g., Gen-4 and Gen-5 Open-APIs).
                          minItems: 1
                        apiType:
                          type: string
                          enum:
                          - openapi
                          description: The type of API specification. Currently only OpenAPI is supported.
                        gatewayConfiguration:
                          type: object
                          description: Configuration settings for API Gateway
                          properties:
                            apiKeyVerification:
                              type: object
                              description: API key verification settings
                              properties:
                                enabled:
                                  type: boolean
                                  description: Enforce API key verification
                                location:
                                  type: string
                                  description: Variable name for API key location
                            rateLimit:
                              type: object
                              description: Rate limiting configuration
                              properties:
                                enabled:
                                  type: boolean
                                  description: Enable rate limiting
                                identifier:
                                  type: string
                                  description: Identifier for rate limiting
                                limit:
                                  type: string
                                  description: Request limit per identifier
                                interval:
                                  type: string
                                  description: Interval for rate limiting
                            quota:
                              type: object
                              description: Quota configuration
                              properties:
                                identifier:
                                  type: string
                                  description: Identifier for quota
                                limit:
                                  type: string
                                  description: Quota limit
                            OASValidation:
                              type: object
                              description: OpenAPI Specification validation settings
                              properties:
                                requestEnabled:
                                  type: boolean
                                  description: Enable request validation
                                responseEnabled:
                                  type: boolean
                                  description: Enable response validation
                                allowUnspecifiedHeaders:
                                  type: boolean
                                  description: Allow unspecified headers
                                allowUnspecifiedQueryParams:
                                  type: boolean
                                  description: Allow unspecified query parameters
                                allowUnspecifiedCookies:
                                  type: boolean
                                  description: Allow unspecified cookies
                            CORS:
                              type: object
                              description: Cross-Origin Resource Sharing settings
                              properties:
                                enabled:
                                  type: boolean
                                  description: Enable CORS
                                allowCredentials:
                                  type: boolean
                                  description: Enable credentials for cross-origin requests
                                allowOrigins:
                                  type: string
                                  description: Allowed origins (CSV)
                                handlePreflightRequests:
                                  type: object
                                  description: Preflight request configuration
                                  properties:
                                    enabled:
                                      type: boolean
                                      description: Enable handling of preflight requests
                                    allowHeaders:
                                      type: string
                                      description: Allowed headers
                                    allowMethods:
                                      type: string
                                      description: Allowed methods
                                    maxAge:
                                      type: integer
                                      description: Cache duration for preflight requests
                            template:
                              type: string
                              description: Pre-configured template for the API
                        implementation:
                          type: string
                          description: The name of the service where the API is implemented
                        path:
                          type: string
                          description: The root path of the API
                        developerUI:
                          type: string
                          description: Path to the developer UI for the API
                        port:
                          type: integer
                          description: Port where the API is exposed
                        resources:
                          type: array
                          items:
                            type: object
                          description: List of resources exposed by the API
                        required:
                          type: boolean
                          description: Indicates if the API is required
                      required:
                      - name
                      - apiType
                      - implementation
                      - path
                      - port
 ```
