### ISSUE TITLE
component: support for multiple versions of APIs on the same component

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#443]
## Description

The Open API programme has versions for each API - see [OpenAPI Directory](https://www.tmforum.org/oda/open-apis/directory) 

The latest generation of APIs are v5, but the majority of deployed APIs are on v4 (and there will be v6, v7 etc in the future).

The Component specification supports an array of specifications for each API (to allow a component to support more than one version of each API, giving its consumers an upgrade path). See [ODA Component spec](https://github.com/tmforum-oda/oda-canvas/blob/bb4fedb1d81721ab9ba23d1ef06d5d9f431f4c3d/release-notes/oda-component-oas-v1.yaml#L88-L238) also copied below:

```
      specification:  
        type: array
        items:
          type: object
          properties:
            url:
              type: string
              format: url
              description: url to the specification of the API. e.g. url to the swagger/OAS file
            version:
              type: string
              description: The version of API specification. For TM Forum Open-APIs this would be the version of the Open-API spec e.g. v4.0.1
        description: >
          Specification of the API. This is an array to allow for multiple specifications (e.g. to support Gen-4 and Gen-5 Open-APIs)
        minItems: 1
 ```

At the moment we don't have a structure in the component specification for the API implementations to be implemented on separate microservices (the `implementation`, `path` and `port` attributes are listed once for the API and not once for each specification/version.)
