### ISSUE TITLE
Component: Multiple namespaces support for "components" in one Canvas deployment

### ISSUE THREAD

**Issue by lekhamaru** [tmforum-oda/oda-canvas#448]
## Description

Currently we have 1 namespace for components in our deployment called 'components'. If we deploy multiple components under 1 canvas, today we are not able to differentiate them within one canvas deployment.
Can we add that feature in the ODA Canvas

**Comment by lekhamaru** [comment]
Is it possible to have multiple namespaces for the multiple components under 1 Canvas deployment

**Comment by ferenc-hechler** [comment]
Currently this is not supported, because some operators define only the `components` namespace as scope:

https://github.com/tmforum-oda/oda-canvas/blob/9803cad6f5e1cc308ea922b8e5b6e45b9bbcd7a0/source/operators/component-management/component-operator-dockerfile#L23

This means ComponentManagementOperator is only triggered for components which are deployed into the configured namespace `components`. Same might apply for other operators.
Technically it is easy to define wildcards like `components*` or even to define a negative list of namespace not to be monitored, e.g. `!canvas*`.

But we also have to test, whether there are other restrictions like resources being deployed by default into the components namespace might not be accessible if a component is deployed into another namespace. VirtualServices and the ComponentGateway might be candidates.

So, the easiest way to find this out is just to try it.   :-)

**Comment by LesterThomas** [comment]
It should be part of the Canvas reference implementation to allow components in different namespaces. We just haven't had the chance to test this out yet. Whilst I'm sure there will be some issues to get this to work, I don't see any fundamental challenges with this.

**Comment by ferenc-hechler** [comment]
Created branch [feature/448_multiple_component_namespaces](https://github.com/tmforum-oda/oda-canvas/tree/feature/448_multiple_component_namespaces) for making experiments with other namespaces.

I replaced the configured component namespaces "components" with "comps448ns" in charts/canvas-oda/values.yaml (5 occurrences)

When installing the modified Canvas I get an error from cert-manager installation:
```
Error: failed post-install: warning: Hook post-install canvas-oda/charts/cert-manager-init/templates/issuer.yaml failed: 1 error occurred:
        * Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://canvas-cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

**Comment by ferenc-hechler** [comment]
Canvas was deployed now without errors, installing the product-catalog component:

```
helm upgrade --install demo-a -n comps448ns feature-definition-and-test-kit/testData/productcatalog-v1
```

the component was deployed successfully:

```
$ kubectl get components -n comps448ns
NAME                              DEPLOYMENT_STATUS
demo-a-productcatalogmanagement   Complete
```

the exposed APIs are ready:

```
$ kubectl get exposedapis -n comps448ns
NAME                                                       API_ENDPOINT                                                                                                 IMPLEMENTATION_READY
demo-a-productcatalogmanagement-metrics                    https://components.ihc-dt.cluster-1.de/demo-a-productcatalogmanagement/metrics                               true
demo-a-productcatalogmanagement-partyrole                  https://components.ihc-dt.cluster-1.de/demo-a-productcatalogmanagement/tmf-api/partyRoleManagement/v4        true
demo-a-productcatalogmanagement-productcatalogmanagement   https://components.ihc-dt.cluster-1.de/demo-a-productcatalogmanagement/tmf-api/productCatalogManagement/v4   true
```

Calling the exposed URL is successful:

![Image](https://github.com/user-attachments/assets/cccfbf98-5865-4e94-9318-227b2aacd304)

So changing the name of the component namespace seems to work good.

Next is to test support of multiple namespaces.

**Comment by ferenc-hechler** [comment]
Chaning Component Operator to support multiple namespaces in charts/oda-canvas/values.yaml:

```
component-operator:
  deployment:
    ...
    monitoredNamespaces: 'comps448ns,comps-a-ns,comps-b-ns'           # comma separated list of namespaces
```

installing the canvas with the modified values.yaml gives an error:

```
$ helm upgrade --install canvas charts/canvas-oda -n canvas --create-namespace --set keycloak.service.type=ClusterIP --set=canvas-vault.enabled=false

  Release "canvas" does not exist. Installing it now.
  Error: 4 errors occurred:
        * namespaces "comps448ns,comps-a-ns,comps-b-ns" not found
        * namespaces "comps448ns,comps-a-ns,comps-b-ns" not found
        * namespaces "comps448ns,comps-a-ns,comps-b-ns" not found
        * namespaces "comps448ns,comps-a-ns,comps-b-ns" not found
```

**Comment by ferenc-hechler** [comment]
created the YAML using the helm template command:

```
helm template canvas charts/canvas-oda -n canvas --create-namespace --set keycloak.service.type=ClusterIP --set=canvas-vault.enabled=false
```

There are five kubernetes objects, which use the `component-operator.deployment.monitoredNamespaces` value as a plain namespace:

```
...
---
# Source: canvas-oda/charts/api-operator-istio/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: comps448ns,comps-a-ns,comps-b-ns
  name: apioperator-role-namespaced
  ...
---
# Source: canvas-oda/charts/component-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: comps448ns,comps-a-ns,comps-b-ns
  name: odacomponent-role-namespaced
  ...
---
# Source: canvas-oda/charts/api-operator-istio/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: comps448ns,comps-a-ns,comps-b-ns
  name: apioperator-rolebinding-namespaced
  ...
---
# Source: canvas-oda/charts/component-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: comps448ns,comps-a-ns,comps-b-ns
  name: odacomponent-rolebinding-namespaced
  ...
---
# Source: canvas-oda/charts/api-operator-istio/templates/ingressGateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: component-gateway
  namespace: comps448ns,comps-a-ns,comps-b-ns
  ...
```

Here one of the five templates affected:

https://github.com/tmforum-oda/oda-canvas/blob/2b9d8a1d41b1efd5aba92c66730d2bc9808d1bc4/charts/component-operator/templates/rbac.yaml#L112-L120

in Line 117 `.Values.deployment.monitoredNamespaces` is used as a single namespace, what is not possible as it is a comma seperated list of namespaces.
