### ISSUE TITLE
Canvas: define range of supported k8s versions for each beta release

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#45]
## Description

As we move the ODA Component standard to a beta version, we should define the range of supported Kubernetes versions, upgrade the operators to support these versions and test against the range.

**Comment by LesterThomas** [comment]
I propose for the current v1beta1 release, we test against Kubernetes v1.25.

**Comment by gjo-satec** [comment]
The latest version released of Rancher is 2.7.0 https://github.com/rancher/rancher/releases/tag/v2.7.0. It doesn't support 1.25 yet

v1.24.6 (Default)
v1.23.12
It'll be supported in the next 2.7.2, which probably will be released before the v1beta1, but we'll need to update the ODA-CA Lab anytime soon.
Related to this task, we need to define not just the range of Kubernetes we support but the version of any dependency third-party we need, such as Cert-manager, Istio, Keycloack , sticky to each of the supported Kubernetes versions.

**Comment by ferenc-hechler** [comment]
Based on the proposal to test "v1beta1" against Kubernetes v1.25 I checked out the branch "updateCRDtov1beta1" and
followed the installation instructions. 

I had the following issues:

The PostgreSQL version "10.8.0" referenced in "keyloak/Chart.yaml" does not exist any more.
I updated to version "12.1.9".

To initialize a correct DB name and user I add the following lines in the "keycloak/values.yaml":

```
global:
  postgresql:
    auth:
      database: "keycloak"
      username: "keycloak"
      password: "keycloakdbuser"
```      

The next error reported is in rbac.yaml: "rbac.authorization.k8s.io/v1beta1" was removed. 

```
*********************************************************************
Installing base canvas
*********************************************************************

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "odacomponent-role-cluster" namespace: "" from "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "odacomponent-rolebinding-cluster" namespace: "" from "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "odacomponent-role-namespaced" namespace: "components" from "": no matches for kind "Role" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "odacomponent-rolebinding-namespaced" namespace: "components" from "": no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first]

Canvas base install failed
```

I changed all 4 occurrences to "rbac.authorization.k8s.io/v1".

But now I get an error and am lost:

```
Error: INSTALLATION FAILED: failed to create resource: CustomResourceDefinition                                                                                                        in version "v1" cannot be handled as a CustomResourceDefinition: json: cannot un                                                                                                       marshal bool into Go struct field JSONSchemaProps.spec.versions.schema.openAPIV3                                                                                                       Schema.properties.properties.properties.items of type []string
```

**Comment by ferenc-hechler** [comment]
Using "Trial and Error" I figured out the problem.

In "oda-component-crd.yaml" required fields are defined as follows:

```
                  dependentAPIs:   
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
[*]                       required: true
                          description: Name of the API that this component is dependent on
                        apitype:
                          type: string
[*]                       required: true
                          enum: [openapi, prometheus]
                          description: The type of API specification. Currently only OpenAPI (swagger) and Prometheus APIs are supported.
                        specification:
                          type: string
                          format: url
                          description: url to the specification of the API. e.g. url to the swagger file
```

The expected format is different, see 
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules

So, the correct syntax is:

```
                  dependentAPIs:   
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the API that this component is dependent on
                        apitype:
                          type: string
                          enum: [openapi, prometheus]
                          description: The type of API specification. Currently only OpenAPI (swagger) and Prometheus APIs are supported.
                        specification:
                          type: string
                          format: url
                          description: url to the specification of the API. e.g. url to the swagger file
[*]                   required:
[*]                   - name
[*]                   - apitype
```
