### ISSUE TITLE
Missing version field  in API specification

### ISSUE THREAD

**Issue by IremGA** [tmforum-oda/oda-canvas#464]
## Long story short

Component operator does not expose **specification.version** and **id** fields of APIs.
In v1beta4 ready for publication repository, reference component specifications have  specification.url and **specification.version** and id fields for each exposed and dependent Apis. 

Sample from v1beta4 Ready For Publication repository :
```
exposedAPIs:
    - id: TMF620
      apiType: openapi
      name: product-catalog-management-api
      required: true
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
        version: v4.0.0
      path:
```

Component Configuration:

```
coreFunction:
    exposedAPIs: 
    - name: productcatalogmanagement
      **specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json"
      - version: v4.0.0**
      implementation: {{.Release.Name}}-prodcatapi
      apiType: openapi
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productCatalogManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productCatalogManagement/v4/docs
      port: 8080
```

The result go how component operator processes : 

```
feature-definition-and-test-kit %kubectl get -o yaml component pc-productcatalogmanagement -n components


apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
....
....
 exposedAPIs:
    - apiType: openapi
      developerUI: /pc-productcatalogmanagement/tmf-api/productCatalogManagement/v4/docs
      gatewayConfiguration: {}
      implementation: pc-prodcatapi
      name: productcatalogmanagement
      path: /pc-productcatalogmanagement/tmf-api/productCatalogManagement/v4
      port: 8080
      **specification:
      - url: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json**
```

Thanks for your consideration!

**Comment by hvaughanattmforum** [comment]
This may be a barrier if the Component specifies that alternative versions of an API are acceptable. How would the service distinguish which API to use/configure/test, etc.?

**Comment by IremGA** [comment]
Let me feed it with one sample.  In component specification version field specifies the base version of the API specification  : 
```
coreFunction:
    dependentAPIs:
    - apiType: openapi
      name: product-catalog-management-api
      specification:
      - url: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/**4.1.0**/swagger/**TMF620_Product_Catalog_Management_API_v4.1.0**_swagger.json
        **version: v4.0.0**
```
