### ISSUE TITLE
component specification ID

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#493]
## Description

The component stream have asked the exposedAPI and dependentAPI to include an ID. These are not used by the Canvas and at present are available inconsistently only in the exposedAPI spec.

It should show

```yaml
    id:
      type: string
      description: This is the id of the API. For TM Forum Open-APIs this would be TMFxxx e.g. TMF620 for Product Catalog Management. 
```
