### ISSUE TITLE
Postgresql parameter name of keycloak is incompatible when upgrade to v13.0.2

### ISSUE THREAD

**Issue by 9n** [tmforum-oda/oda-canvas#73]
When keycloak upgrade to v13.0.2, postgresql parameter in file located `installation/canvas-oda/values.yaml`
```
  postgresql:
    enabled: true
    postgresqlUsername: "keycloak"
    postgresqlPassword: "keycloakdbuser"
    postgresqlDatabase: "keycloak"
```

should be changed with:
```
  postgresql:
    enabled: true
    auth:
      username: "keycloak"
      password: "keycloakdbuser"
      database: "keycloak"
```
