### ISSUE TITLE
Component Specification: adding more properties for Event mechanisms

### ISSUE THREAD

**Issue by csotiriou** [tmforum-oda/oda-canvas#90]
The component specification right now involves having a limited set of properties

```
subscribedEvents:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        href:
          type: string
```

Seems somewhat limiting, especially since the spec of the oda-subscribednotification-crd includes the `x-kubernetes-preserve-unknown-fields: true` field. 

Should something like this exist in the component spec as well?
